apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: jpa-bcrypt-mysql
  name: jpa-bcrypt-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpa-bcrypt-mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jpa-bcrypt-mysql
    spec:
      containers:
      - image: nikoleye/jpa-bcrypt-practice:1.0.2-MYSQL
        imagePullPolicy: IfNotPresent
        name: jpa-bcrypt-mysql
        resources:
          requests: 
            cpu: "250m"
        env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
      restartPolicy: Always            
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: jpa-bcrypt-mysql
  name: jpa-bcrypt-mysql
  namespace: default
spec:
  ports:
  -  port: 8100
     protocol: TCP
     targetPort: 8100
  selector:
    app: jpa-bcrypt-mysql
  sessionAffinity: None
  type: LoadBalancer